name: Build Artemis Editor
run-name: ${{ github.actor }} Artemis Editor Build
on:
  push:
    branches: ["main"]
jobs:
  build-artemis-editor:     
    #strategy:
    #  matrix:
    #    configuration: [Debug, Release]   
    env:
      SolutionName: Artemis\Artemis.sln
      Configuration: Debug

    runs-on: windows-latest
    steps:
    - name: Fetch Latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore Target
      run: msbuild $env:SolutionName /t:Restore /p:Configuration=$env:Configuration /m:20
      
    - name: Build Target
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration /m:20
