
name: "[Runtime] - Build"
run-name: Artemis Runtime
  
on:
  push:
    branches: ["Runtime"]
    
jobs:      
  Build-Debug:
    env:
      SolutionName: ArtemisRuntime\DX12_Project.sln
      Configuration: Debug
      Cores: 20

    runs-on: windows-latest
    steps:
    - name: Fetch Latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Cache Nuget.exe
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Restore Nuget Packages
      run: nuget restore $env:SolutionName
      
    - name: Build Target
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration /m:$env:Cores
    
    - name: 'Upload Debug Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: ArtemisRuntime_Debug
      
  Build-Release:
    env:
      SolutionName: ArtemisRuntime\DX12_Project.sln
      Configuration: Release
      Cores: 20

    runs-on: windows-latest
    steps:
    - name: Fetch Latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    
    - name: Cache Nuget.exe
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Restore Nuget Packages
      run: nuget restore $env:SolutionName
      
    - name: Build Target
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration /m:$env:Cores
    
    # - name: 'Upload Release Artifact'
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ArtemisRuntime_Release
  
  # Perform-UnitTests:
  #   env:
  #     SolutionName: ArtemisRuntime\DX12_Project.sln
  #   runs-on: windows-latest
  #   steps:
  #   - name: Download Runtime Artefacts
  #     uses: 
