name: "[Editor] - Build"
run-name: Artemis Editor
  
on:
  push:
    branches: ["Tools"]
    
jobs:      
  Build-Debug:
    env:
      SolutionName: ArtemisEditor\Artemis.sln
      Configuration: Debug
      Cores: 20

    runs-on: windows-latest
    steps:
    - name: Fetch Latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Cache .NET Core
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: "C:\\Program Files\\dotnet"
        key: ${{ runner.os }}-dotnet-7
        restore-keys: ${{ runner.os }}-dotnet-7
        
    - name: Install .NET Core
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Restore Target
      run: msbuild $env:SolutionName /t:Restore /p:Configuration=$env:Configuration /m:$env:Cores
      
    - name: Build Target
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration /m:$env:Cores
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ArtemisEditor_Debug
        path: |
          ArtemisEditor\**\bin\Debug\**\*.*

  Build-Release:
    env:
      SolutionName: ArtemisEditor\Artemis.sln
      Configuration: Release
      Cores: 20

    runs-on: windows-latest
    steps:
    - name: Fetch Latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Cache .NET Core
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: "C:\\Program Files\\dotnet"
        key: ${{ runner.os }}-dotnet-7
        restore-keys: ${{ runner.os }}-dotnet-7
        
    - name: Install .NET Core
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Restore Target
      run: msbuild $env:SolutionName /t:Restore /p:Configuration=$env:Configuration /m:$env:Cores
      
    - name: Build Target
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration /m:$env:Cores
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ArtemisEditor_Release
        path: |
          ArtemisEditor\**\bin\Release\**\*.*

  Perform-UnitTests-Debug:
    needs: [Build-Debug]
    runs-on: windows-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ArtemisEditor_Debug

    - name: Cache .NET Core
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: "C:\\Program Files\\dotnet"
        key: ${{ runner.os }}-dotnet-7
        restore-keys: ${{ runner.os }}-dotnet-7
        
    - name: Install .NET Core
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Run Tests
      shell: pwsh
      run: |
        $TestDlls = Get-ChildItem -Path .\ -Filter *.UnitTests.dll -Recurse
        $VSTestArgs = @()
        foreach($Dll in $TestDlls) { $VSTestArgs = $VSTestArgs + $Dll.FullName }
        echo $VSTestArgs
        foreach($Dll in $TestDlls) { dotnet test $Dll }

  Perform-UnitTests-Release:
    needs: [Build-Release]
    runs-on: windows-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ArtemisEditor_Release

    - name: Cache .NET Core
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: "C:\\Program Files\\dotnet"
        key: ${{ runner.os }}-dotnet-7
        restore-keys: ${{ runner.os }}-dotnet-7
        
    - name: Install .NET Core
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Run Tests
      shell: pwsh
      run: |
        $TestDlls = Get-ChildItem -Path .\ -Filter *.UnitTests.dll -Recurse
        $VSTestArgs = @()
        foreach($Dll in $TestDlls) { $VSTestArgs = $VSTestArgs + $Dll.FullName }
        echo $VSTestArgs
        foreach($Dll in $TestDlls) { dotnet test $Dll }