name: "[Debug]: Artemis Editor"
run-name: Debug - Artemis Editor - ${{ github.actor }}
  
on:
  push:
    branches: ["main"]
    
jobs:       
#    - name: Cache Nuget Dependencies
#      id: cache-nuget
#      uses: actions/cache@v3
#      with:
#        path: ~/.nuget/packages
#        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-nuget
#          
#    - name: Install dependencies
#      run: dotnet add package Newtonsoft.Json --version 12.0.1
      
  Build-Solution:
    env:
      SolutionName: Artemis\Artemis.sln
      Configuration: Debug
      Cores: 20

    runs-on: windows-latest
    steps:
    - name: Fetch Latest
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Cache .NET Core
      id: cache-dotnet
      uses: actions/cache@v3
      with:
        path: '.\.dotnet'
        key: ${{ runner.os }}-dotnet-7
        restore-keys: ${{ runner.os }}-dotnet-7
        
    - name: Install .NET Core
      if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Restore Target
      run: msbuild $env:SolutionName /t:Restore /p:Configuration=$env:Configuration /m:$env:Cores
      
    - name: Build Target
      run: msbuild $env:SolutionName /t:Build /p:Configuration=$env:Configuration /m:$env:Cores
