name: "Staging - Pull"
run-name: Staging - Pull Request - ${{ github.ref_name }}
  
on:
  workflow_run:
    workflows: [ "Dev - Build" ]
    types:
    - completed

jobs:
  Create-PR:
    env:
      SourceRef: Development
      TargetRef: Staging

    runs-on: windows-latest
    - name: Checkout Development
      uses: actions/checkout@v3
      with:
        ref: $env:SourceRef

    - name: Create Pull Request (Development -> Staging)
      uses: peter-evans/create-pull-request@v5
      with:
        base: $env:TargetRef
        branch: $env:SourceRef